## The slices image resource (id 1050), per the Adobe Photoshop File Format
## Specification.
##
## Version 6 is a fixed binary layout: a bounding rect, the group name, then
## per slice the ids, origin, an optional layer id, name, type, rect, the
## URL / target / message / alt strings, cell text and alignment, and a
## background colour. It may be followed by a versioned descriptor carrying
## extra per-slice data such as layer-slice outsets.
##
## Versions 7 and 8 store everything as one versioned descriptor with the keys
## `baseName`, `bounds` and `slices`.
##
## `writeSlices` emits version 6, the layout every Photoshop version reads,
## and appends the outsets descriptor when any slice has them. Unknown fields
## are not modelled here; a caller that needs a byte-exact round trip keeps
## the raw resource bytes while the slices are unchanged.

import std/options

import ./descriptor
import ./error
import ./io
import ./resources

type
  SliceRecord* = object
    ## One slice. Field order follows the spec, which is also the write order.
    id*: uint32                ## slice id
    groupId*: uint32           ## group id
    origin*: uint32            ## 0 auto-generated, 1 layer-based, 2 user-drawn
    layerId*: Option[uint32]   ## layer id, present only when `origin == 1`
    name*: string              ## slice name
    kind*: uint32              ## 0 no image, 1 image, 2 table
    rect*: array[4, int32]     ## left, top, right, bottom, in document pixels
    url*: string
    target*: string            ## target frame
    message*: string           ## status-bar message
    alt*: string               ## alt tag
    cellTextIsHtml*: bool
    cellText*: string
    horizontalAlign*: uint32
    verticalAlign*: uint32
    color*: array[4, uint8]    ## alpha, red, green, blue
    outsets*: array[4, int32]  ## top, left, bottom, right; layer-based slices

  SlicesResource* = object
    ## The whole resource. `version` is whatever was read (6, 7 or 8);
    ## writing always produces 6 unless `writeSlicesDescriptor` is used.
    version*: uint32
    bounds*: array[4, int32]   ## top, left, bottom, right
    groupName*: string         ## the slice group's base name
    slices*: seq[SliceRecord]  ## as Photoshop saves them, auto-generated included

# --- descriptor helpers (versions 7/8 and the version 6 tail) ---------------

proc descriptorInt(d: Descriptor, key: string, fallback: int32): int32 =
  ## An integer from any of the numeric OSTypes Photoshop uses for it.
  let v = d.get(key)
  if v.isNone:
    return fallback
  case v.get().kind
  of vInteger: v.get().integer
  of vLargeInteger: int32(clamp(int64(v.get().large), -2147483648'i64, 2147483647'i64))
  of vDouble: int32(v.get().double)
  of vUnitFloat: int32(v.get().floatUnitValue)
  else: fallback

proc descriptorText(d: Descriptor, key: string): string {.inline.} =
  d.getText(key)

proc descriptorEnum(d: Descriptor, key: string): Option[string] =
  let v = d.get(key)
  if v.isNone or v.get().kind != vEnumerated:
    return none(string)
  some(v.get().valueId.asString())

proc descriptorBool(d: Descriptor, key: string): bool {.inline.} =
  d.getBool(key)

proc descriptorBounds(d: Descriptor, key: string): array[4, int32] =
  ## Bounds as the descriptor stores them: top, left, bottom, right. All
  ## zeros when the key is missing or is not a descriptor.
  let b = d.getDescriptor(key)
  if b.isNone:
    return [0'i32, 0'i32, 0'i32, 0'i32]
  let g = b.get()
  result = [descriptorInt(g, "Top ", 0), descriptorInt(g, "Left", 0),
            descriptorInt(g, "Btom", 0), descriptorInt(g, "Rght", 0)]

proc originFromName(s: string): uint32 =
  ## The `ESliceOrigin` enumerated value as the numeric origin.
  if s == "autoGenerated": 0'u32
  elif s == "layerGenerated" or s == "layer": 1'u32
  else: 2'u32

proc kindFromName(s: string): uint32 =
  ## The `ESliceType` enumerated value as the numeric kind.
  if s == "noImage": 0'u32
  elif s == "Tbl " or s == "table": 2'u32
  else: 1'u32

proc sliceFromDescriptor(d: Descriptor): SliceRecord =
  let b = descriptorBounds(d, "bounds")
  var color: array[4, uint8]
  let bgType = descriptorEnum(d, "bgColorType")
  let bg = d.getDescriptor("bgColor")
  if bgType.isSome and bgType.get() == "Clr " and bg.isSome:
    let c = bg.get()
    let g = proc(k: string): uint8 =
      uint8(clamp(descriptorInt(c, k, 0), 0'i32, 255'i32))
    # Photoshop omits `alpha` for an opaque colour.
    let alpha = if c.has("alpha"): g("alpha") else: 255'u8
    color = [alpha, g("Rd  "), g("Grn "), g("Bl  ")]
  let layerIdVal = d.get("layerID")
  result = SliceRecord(
    id: uint32(descriptorInt(d, "sliceID", 0)),
    groupId: uint32(descriptorInt(d, "groupID", 0)),
    origin: (if descriptorEnum(d, "origin").isSome:
        originFromName(descriptorEnum(d, "origin").get()) else: 2'u32),
    layerId: (if layerIdVal.isSome: some(uint32(descriptorInt(d, "layerID", 0)))
              else: none(uint32)),
    name: descriptorText(d, "Nm  "),
    kind: (if descriptorEnum(d, "Type").isSome:
        kindFromName(descriptorEnum(d, "Type").get()) else: 1'u32),
    # Descriptor bounds are top/left/bottom/right; records use left/top/right/bottom.
    rect: [b[1], b[0], b[3], b[2]],
    url: descriptorText(d, "url"),
    target: descriptorText(d, "null"),
    message: descriptorText(d, "Msge"),
    alt: descriptorText(d, "altTag"),
    cellTextIsHtml: descriptorBool(d, "cellTextIsHTML"),
    cellText: descriptorText(d, "cellText"),
    color: color,
    outsets: [descriptorInt(d, "topOutset", 0), descriptorInt(d, "leftOutset", 0),
              descriptorInt(d, "bottomOutset", 0), descriptorInt(d, "rightOutset", 0)])

proc boundsValue(tlbr: array[4, int32]): Value =
  ## An `Rct1` descriptor in top, left, bottom, right order.
  descriptorValue(newDescriptor("Rct1")
    .with("Top ", intValue(tlbr[0]))
    .with("Left", intValue(tlbr[1]))
    .with("Btom", intValue(tlbr[2]))
    .with("Rght", intValue(tlbr[3])))

# --- parsing ----------------------------------------------------------------

proc parseSlicesV6(r: var Reader, limits: Limits): SlicesResource =
  ## The fixed binary layout, plus an optional trailing descriptor whose only
  ## role is to carry the outsets.
  for i in 0 ..< 4:
    result.bounds[i] = r.readI32BE()
  result.groupName = unicodeToString(r.readUnicodeUnits())
  let n = int64(r.readU32BE())
  limits.checkCount(n, r.remaining.int64, 16'i64, "slices")
  result.slices = newSeq[SliceRecord](int(n))
  for i in 0 ..< int(n):
    var s: SliceRecord
    s.id = r.readU32BE()
    s.groupId = r.readU32BE()
    s.origin = r.readU32BE()
    # The layer id is present only for layer-based slices.
    if s.origin == 1:
      s.layerId = some(r.readU32BE())
    s.name = unicodeToString(r.readUnicodeUnits())
    s.kind = r.readU32BE()
    for j in 0 ..< 4:
      s.rect[j] = r.readI32BE()
    s.url = unicodeToString(r.readUnicodeUnits())
    s.target = unicodeToString(r.readUnicodeUnits())
    s.message = unicodeToString(r.readUnicodeUnits())
    s.alt = unicodeToString(r.readUnicodeUnits())
    s.cellTextIsHtml = r.readU8() != 0
    s.cellText = unicodeToString(r.readUnicodeUnits())
    s.horizontalAlign = r.readU32BE()
    s.verticalAlign = r.readU32BE()
    s.color = [r.readU8(), r.readU8(), r.readU8(), r.readU8()]
    result.slices[i] = s
  result.version = 6
  # A trailing descriptor adds per-slice extras such as outsets. It is
  # optional, so a damaged one is ignored rather than failing the resource.
  if r.remaining() >= 4:
    let tail = r.peekRest()
    try:
      let vd = parseVersionedDescriptor(tail, limits)
      let items = vd.descriptor.get("slices")
      if items.isSome and items.get().kind == vList:
        for item in items.get().items:
          if item.kind != vDescriptor:
            continue
          let extra = sliceFromDescriptor(item.descriptor)
          for s in result.slices.mitems:
            if s.id == extra.id:
              s.outsets = extra.outsets
    except PsdError:
      discard # an optional tail that does not parse is simply ignored

proc parseSlices*(data: Span, limits = defaultLimits()): SlicesResource =
  ## Parse resource 1050 data, versions 6, 7 and 8.
  var r = initReader(data)
  let version = r.readU32BE()
  result.version = version
  case version
  of 6:
    result = parseSlicesV6(r, limits)
  of 7, 8:
    let tail = r.peekRest()
    let vd = parseVersionedDescriptor(tail, limits)
    result.bounds = descriptorBounds(vd.descriptor, "bounds")
    result.groupName = descriptorText(vd.descriptor, "baseName")
    let items = vd.descriptor.get("slices")
    if items.isSome and items.get().kind == vList:
      for item in items.get().items:
        if item.kind == vDescriptor:
          result.slices.add(sliceFromDescriptor(item.descriptor))
  else:
    unsupported("slices resource version " & $version)

# --- writing ----------------------------------------------------------------

proc writeUnicodeString(w: var Writer, s: string) {.inline.} =
  w.writeUnicode(s)

proc writeSlices*(s: SlicesResource): string =
  ## Serialize as version 6. A trailing descriptor carrying the outsets is
  ## appended when any slice has them, the way Photoshop extends this layout.
  var w = initWriter()
  w.putU32(6)
  for v in s.bounds:
    w.putI32(v)
  writeUnicodeString(w, s.groupName)
  w.putU32(uint32(s.slices.len))
  for slice in s.slices:
    w.putU32(slice.id)
    w.putU32(slice.groupId)
    w.putU32(slice.origin)
    if slice.origin == 1:
      w.putU32(if slice.layerId.isSome: slice.layerId.get() else: 0'u32)
    writeUnicodeString(w, slice.name)
    w.putU32(slice.kind)
    for v in slice.rect:
      w.putI32(v)
    writeUnicodeString(w, slice.url)
    writeUnicodeString(w, slice.target)
    writeUnicodeString(w, slice.message)
    writeUnicodeString(w, slice.alt)
    w.putU8(if slice.cellTextIsHtml: 1'u8 else: 0'u8)
    writeUnicodeString(w, slice.cellText)
    w.putU32(slice.horizontalAlign)
    w.putU32(slice.verticalAlign)
    w.putBytes(slice.color)
  var anyOutsets = false
  for slice in s.slices:
    if slice.outsets != [0'i32, 0'i32, 0'i32, 0'i32]:
      anyOutsets = true
      break
  if anyOutsets:
    var list: seq[Value] = @[]
    for slice in s.slices:
      list.add(descriptorValue(newDescriptor("slice")
        .with("sliceID", intValue(int32(slice.id)))
        .with("topOutset", intValue(slice.outsets[0]))
        .with("leftOutset", intValue(slice.outsets[1]))
        .with("bottomOutset", intValue(slice.outsets[2]))
        .with("rightOutset", intValue(slice.outsets[3]))))
    w.put(newVersioned(newDescriptor("null").with("slices", listValue(list))).toBytes())
  w.toString()

proc writeSlicesDescriptor*(s: SlicesResource): string =
  ## Serialize in the version 7 descriptor form, which is what newer Photoshop
  ## versions write.
  var list: seq[Value] = @[]
  for slice in s.slices:
    let origin = case slice.origin
      of 0: "autoGenerated"
      of 1: "layerGenerated"
      else: "userGenerated"
    let kind = case slice.kind
      of 0: "noImage"
      of 2: "Tbl "
      else: "Img "
    var d = newDescriptor("slice")
      .with("sliceID", intValue(int32(slice.id)))
      .with("groupId", intValue(int32(slice.groupId)))
      .with("origin", enumValue("ESliceOrigin", origin))
    if slice.origin == 1 and slice.layerId.isSome:
      d = d.with("layerID", intValue(int32(slice.layerId.get())))
    d = d
      .with("Nm  ", textValue(slice.name))
      .with("Type", enumValue("ESliceType", kind))
      # The descriptor stores top/left/bottom/right; records are left/top/right/bottom.
      .with("bounds", boundsValue([slice.rect[1], slice.rect[0], slice.rect[3], slice.rect[2]]))
      .with("url", textValue(slice.url))
      .with("null", textValue(slice.target))
      .with("Msge", textValue(slice.message))
      .with("altTag", textValue(slice.alt))
      .with("cellTextIsHTML", boolValue(slice.cellTextIsHtml))
      .with("cellText", textValue(slice.cellText))
      .with("horzAlign", enumValue("ESliceHorzAlign", "default"))
      .with("vertAlign", enumValue("ESliceVertAlign", "default"))
      .with("bgColorType", enumValue("ESliceBGColorType", "None"))
      .with("topOutset", intValue(slice.outsets[0]))
      .with("leftOutset", intValue(slice.outsets[1]))
      .with("bottomOutset", intValue(slice.outsets[2]))
      .with("rightOutset", intValue(slice.outsets[3]))
    list.add(descriptorValue(d))
  let root = newDescriptor("null")
    .with("bounds", boundsValue(s.bounds))
    .with("slices", listValue(list))
    .with("baseName", textValue(s.groupName))
  var w = initWriter()
  w.putU32(7)
  w.put(newVersioned(root).toBytes())
  w.toString()

proc slices*(resources: openArray[ImageResource],
    limits = defaultLimits()): Option[SlicesResource] =
  ## The slices resource (1050), or `none` when absent or unparseable.
  let res = getResource(resources, SlicesId)
  if res.isNone:
    return none(SlicesResource)
  try:
    some(parseSlices(res.get().data, limits))
  except PsdError:
    none(SlicesResource)

proc parseSlices*(data: string, limits = defaultLimits()): SlicesResource =
  parseSlices(toSpan(data), limits)
